/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface DeviceCodeResponse {
  deviceCode: string
  userCode: string
  verificationUri: string
  verificationUriComplete?: string
  expiresIn: number
  interval?: number
}
export interface TokenSet {
  accessToken: string
  refreshToken?: string
  tokenType: string
  expiresIn?: number
  scope?: string
  receivedAt: string
}
export interface AuthState {
  token: TokenSet
  expiresAt: string
}
export interface UserProfile {
  id: string
  email: string
  emailVerified: boolean
  name?: string
  image?: string
  createdAt: string
  updatedAt: string
}
/** Standalone function for full device login flow. */
export declare function deviceLogin(baseUrl: string, clientId: string, appName?: string | undefined | null): Promise<AuthState>
/** Standalone function to logout. */
export declare function deviceLogout(baseUrl: string, clientId: string, appName?: string | undefined | null): Promise<void>
export declare class SabishiiAuth {
  constructor(baseUrl: string, clientId: string, appName?: string | undefined | null)
  /** Request a device code to start the device authorization flow. */
  requestDeviceCode(): Promise<DeviceCodeResponse>
  /** Poll for token after user authorizes the device. */
  pollForToken(deviceCode: string): Promise<TokenSet>
  /** Refresh the access token using a stored refresh token. */
  refreshToken(): Promise<TokenSet>
  /** Revoke the refresh token and clear stored credentials. */
  logout(): Promise<void>
  /** Load the currently stored auth state from keychain. */
  loadState(): AuthState | null
  /** Check if the stored token is expired. */
  isTokenExpired(): boolean
  /** Get the current user's profile. */
  getUserProfile(): Promise<UserProfile>
  /** Get just the user ID. */
  getUserId(): Promise<string>
}
