/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface DeviceCodeResponse {
  deviceCode: string
  userCode: string
  verificationUri: string
  verificationUriComplete?: string
  expiresIn: number
  interval?: number
}
export interface TokenSet {
  accessToken: string
  refreshToken?: string
  tokenType: string
  expiresIn?: number
  scope?: string
  receivedAt: string
}
export interface AuthState {
  token: TokenSet
  expiresAt: string
}
export interface LogoutResult {
  localCleared: boolean
  remoteRevoked: boolean
}
export interface UserProfile {
  id: string
  email: string
  emailVerified: boolean
  name?: string
  image?: string
  createdAt: string
  updatedAt: string
}
/** Standalone function for the full interactive device login flow. */
export declare function deviceLogin(baseUrl: string, clientId: string): Promise<AuthState>
/** Standalone function to clear local credentials and attempt remote revocation. */
export declare function deviceLogout(baseUrl: string, clientId: string): Promise<LogoutResult>
export declare class SabishiiAuth {
  constructor(baseUrl: string, clientId: string)
  /** Request a device code to start the device authorization flow. */
  requestDeviceCode(): Promise<DeviceCodeResponse>
  /**
   * Poll using only a device code. Deprecated; use pollForDeviceToken so
   * server-provided expiry and interval values are preserved.
   */
  pollForToken(deviceCode: string): Promise<TokenSet>
  /** Poll for a token using the complete server-provided device response. */
  pollForDeviceToken(device: DeviceCodeResponse): Promise<TokenSet>
  /** Refresh the access token using a stored single-use refresh token. */
  refreshToken(): Promise<TokenSet>
  /** Clear local credentials and report whether remote revocation succeeded. */
  logout(): Promise<LogoutResult>
  /** Load the currently stored auth state from keychain. */
  loadState(): AuthState | null
  /** Check if the stored token is expired. */
  isTokenExpired(): boolean
  /** Get the current user's profile. */
  getUserProfile(): Promise<UserProfile>
  /** Get just the user ID. */
  getUserId(): Promise<string>
}
